# Generated by Django 4.2.16 on 2024-10-31 15:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Shape',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shape_type', models.CharField(choices=[('rectangle', 'Rectangle'), ('circle', 'Circle'), ('line', 'Line'), ('text', 'Text')], max_length=20)),
                ('x', models.FloatField()),
                ('y', models.FloatField()),
                ('properties', models.JSONField()),
                ('style', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_shapes', to=settings.AUTH_USER_MODEL)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shapes', to='projects.project')),
            ],
            options={
                'ordering': ['order', 'created_at'],
            },
        ),
    ]
